name: Export release
on:
  schedule:
    - cron: '0 20 * * 1,5'
  push:
    branches:
      - master
jobs:
  export:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: npm install
      - name: Export
        run: npm run export
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            export/*
          tag_name: Release - $(date + '%Y-%m-%d')